### ISSUE TITLE
Solr option doesn't work

### ISSUE THREAD

**Issue by bondjimbond** [LeidenUniversityLibrary/islandora_compound_parent_metadata_block#1]
This block module is a great replacement for https://github.com/mjordan/islandora_compound_parent_metadata! I'm trying it out, and noticed a bug...

If you select the Solr option instead of the DC option in the block configuration, you get problems:

> Document not present in Solr while generating the metadata display for my:object. Try reloading the page, or contact an administrator if this issue persists.

The document is present in Solr, so there must be a problem with how this module is querying Solr, I guess?

**Comment by bondjimbond** [comment]
Update: It does work provided the Compound Object CModel has a Solr Metadata Display Profile associated with it!

Perhaps it would be worthwhile to check for an association, and return an error (No metadata display profile configured for CModel) if it doesn't exist.

**Comment by lucasvanschaik** [comment]
I think that is it not the responsibility of this module to do that: the Islandora_solr_metadata display template is used for displaying the metadata, it should handle this situation more elegantly.

**Comment by bondjimbond** [comment]
@lucasvanschaik islandora_solr_metadata appears to check if there is a metadata display profile associated with the CModel, and if not, switches to the stock DC display. I suspect that when this module passes info to the template, since it's specifically requesting the Solr version, it skips that check.
