### ISSUE TITLE
Block does not appear when viewing parent

### ISSUE THREAD

**Issue by bondjimbond** [LeidenUniversityLibrary/islandora_compound_parent_metadata_block#2]
By default, viewing a Compound Object shows you the first child, including its theme and metadata.

It does NOT show you the Compound Parent Metadata Block.

We need a way to make sure the block displays when viewing parents, not just their children, since the parent metadata is never actually seen.

**Comment by bondjimbond** [comment]
PR: #3

**Comment by lucasvanschaik** [comment]
You are right, that is an error.
We use the Compound Solution Pack with the option "Redirect to first child when a compound object is requested" on (an option we contributed to that SP), so we don't display the compound object anyway.

**Comment by lucasvanschaik** [comment]
Solved with PR #3 thanks to @bondjimbond
